# Generated by Django 4.0.3 on 2022-04-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departments',
            table='departments',
        ),
    ]
