# Generated by Django 4.0.3 on 2022-04-09 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ManyToManyField(related_name='appointments_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
