# Generated by Django 4.0.3 on 2022-04-09 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('user_app', '0002_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='doctorfields',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.departments'),
        ),
        migrations.AddField(
            model_name='doctorfields',
            name='img',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctorfields',
            name='short_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        # migrations.AlterModelTable(
        #     name='appointment',
        #     table='patient_appointments',
        # ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
        migrations.AlterModelTable(
            name='doctorfields',
            table='doctor_information',
        ),
        migrations.AlterModelTable(
            name='medicalhistory',
            table='patient_medical_history',
        ),
        migrations.AlterModelTable(
            name='medicalstatus',
            table='patient_medical_status',
        ),
        # migrations.AlterModelTable(
        #     name='upcomingappointments',
        #     table='patient_upcoming_appointments',
        # ),
        migrations.AlterModelTable(
            name='usercontacts',
            table='user_contact_information',
        ),
    ]
