# Generated by Django 4.0.3 on 2022-04-12 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_customuser_options_doctorfields_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorfields',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
