# Generated by Django 4.0.3 on 2022-04-12 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_doctorfields_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$'), django.core.validators.MinLengthValidator(12)], verbose_name='iin'),
        ),
    ]
