# Generated by Django 4.0.3 on 2022-04-12 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontacts',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
