# Generated by Django 4.0.3 on 2022-04-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_remove_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
