# Generated by Django 4.0.3 on 2022-04-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_alter_doctorfields_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='disease',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
