# Generated by Django 4.0.3 on 2022-04-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_medicalhistory_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalstatus',
            name='blood_group',
            field=models.CharField(default='A+', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalstatus',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
