# Generated by Django 4.0.3 on 2022-04-14 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_medicalstatus_blood_group_alter_medicalstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
