# Generated by Django 4.0.3 on 2022-04-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_alter_medicalstatus_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingappointments',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='UpcomingAppointments',
        ),
    ]
