# Generated by Django 4.0.3 on 2022-04-18 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_appointment', models.DateField()),
                ('upcoming_appointment', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_upcoming_appointments',
            },
        ),
        migrations.CreateModel(
            name='AppointmentDay',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_day', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointment_day',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(choices=[(1, '9:00-9:30'), (2, '9:30-10:00'), (3, '10:00-10:30'), (4, '10:30-11:00'), (5, '11:00-11:30'), (6, '11:30-12:00'), (7, '12:00-12:30'), (8, '12:30-13:00'), (9, '14:30-15:00'), (10, '15:00-15:30'), (11, '15:00-15:30'), (12, '16:00-16:30'), (13, '16:30-17:00'), (14, '17:00-17:30'), (15, '17:30-18:00')])),
                ('description', models.CharField(max_length=200)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_event', to='appointments.appointmentday')),
                ('doctor', models.ManyToManyField(related_name='appointments_list', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_appointments',
            },
        ),
    ]
