# Generated by Django 4.0.3 on 2022-04-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_doctor_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medicine',
            field=models.TextField(blank=True, null=True),
        ),
    ]
